name: Build CLI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: [1.21.x]

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up dependencies
      run: go mod download

    - name: Build on Windows
      if: runner.os == 'Windows'
      run: go build -o correa-cli.exe

    - name: Build on Unix
      if: runner.os != 'Windows'
      run: go build -o correa-cli
      shell: bash

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: correa-cli-${{ matrix.os }}
        path: |
          correa-cli*
